account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('sign-in/', views.AuthorLogin.as_view(), name='login'),
    path('sign-out/', views.AuthorLogout.as_view(), name='logout'),
    path('auth/', views.auth, name='auth'),
]

blog/urls.py
from django.urls import path

from . import views


app_name = 'blog'

urlpatterns = [
    path('<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    path('', views.PostList.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_tag_list, name='post_tag_list'),
    path('create/', views.PostCreate.as_view(), name='post_create'),
    path('<int:pk>/edit/', views.PostUpdate.as_view(), name='post_edit'),
    path('<int:pk>/delete/', views.PostDelete.as_view(), name='post_del'),
    path('ajax/tag/set/', views.post_tag_set, name='post_tag_set'),
]

chat/urls.py
from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.contact, name='contact'),
    path('<int:room_id>/', views.room, name='room'),
]

upload/urls.py
from django.urls import path

from . import views

app_name = 'upload'

urlpatterns = [
    path("", views.UploadView.as_view(), name="upload"),
]

blog/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

from taggit.managers import TaggableManager

from .utils.md_normalize import normalize

from io import StringIO


# Create your models here.
class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE, related_name='posts')
    publish = models.DateTimeField(null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES,
                              default='draft')
    title = models.CharField(max_length=250)
    body = models.TextField()
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.pk])

    @property
    def normalized_body(self):
        return normalize(StringIO(self.body))

blog/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.forms import modelform_factory
from django import forms
from django.http import (HttpResponseRedirect, HttpResponseForbidden,
    HttpResponseNotAllowed, JsonResponse)
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.exceptions import PermissionDenied
from django.db.models import Q

from .models import Post

from taggit.models import Tag


# Create your views here.
class BlogAppMixin:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['section'] = 'blog'
        return context


class PostDetail(BlogAppMixin, DetailView):
    model = Post
    context_object_name = 'post'


class PostList(BlogAppMixin, ListView):
    model = Post
    paginate_by = 10
    context_object_name = 'posts'

    def get_queryset(self):
        if self.request.user.is_authenticated:
            q = Q(status="published") | Q(author=self.request.user)
        else:
            q = Q(status="published")
        qs = super().get_queryset().filter(q).order_by('-created')
        return qs


class PostEditMixin:
    model = Post
    fields = ['title', 'body', 'status']

    def get_form_class(self):
        """return customize post modelform class"""
        model = self.model
        widgets = {
            'status': forms.RadioSelect(choices=Post.STATUS_CHOICES)
        }
        return modelform_factory(model, fields=self.fields, widgets=widgets)


class AuthorRequiredMixin:
    def get_object(self, query_set=None):
        object = super().get_object(query_set)
        if self.request.user == object.author:
            return object
        raise PermissionDenied("You are not allowed to do this!")


@method_decorator(login_required, name='dispatch')
class PostCreate(BlogAppMixin, PostEditMixin, CreateView):
    def form_valid(self, form):
        post = form.save(commit=False)
        post.author = self.request.user
        if not post.publish and post.status == 'published':
            post.publish = timezone.now()
        post.save()
        self.object = post
        return HttpResponseRedirect(self.get_success_url())


@method_decorator(login_required, name='dispatch')
class PostUpdate(BlogAppMixin, AuthorRequiredMixin, PostEditMixin, UpdateView):
    def form_valid(self, form):
        post = form.save(commit=False)
        if not post.publish and post.status == 'published':
            post.publish = timezone.now()
        post.save()
        self.object = post
        return HttpResponseRedirect(self.get_success_url())


@method_decorator(login_required, name='dispatch')
class PostDelete(BlogAppMixin, AuthorRequiredMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post_list')


def post_tag_list(request, tag_slug):
    tag = get_object_or_404(Tag, slug=tag_slug)
    posts = Post.objects.filter(tags__in=[tag])
    page = request.GET.get('page', 1)
    paginator = Paginator(posts, 10)
    try:
        page_obj = paginator.get_page(page)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    return render(request, 'blog/post_list.html', {
        'posts': posts, 'is_paginated': True, 'page_obj': page_obj,
    })


def post_tag_set(request):
    if request.method == 'POST':
        tags = request.POST.getlist('tags')
        pk = request.POST.get('post_id')
        post = get_object_or_404(Post, pk=pk)
        if post.author != request.user:
            return HttpResponseNotAllowed('users not post author')
        post.tags.set(*tags)
        tag_objects = post.tags.all()
        tag_dict = {tag.name: tag.slug for tag in tag_objects}
        res = {'code': 'success', 'tags': tag_dict}
        return JsonResponse(res)
    else:
        return HttpResponseNotAllowed('only post method allowed')


def index(request):
    return render(request, 'blog/index.html')

blog/templates/blog/base.html
{% load static %}
{% load blog_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}Blog{% endblock %}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'blog/base.css' %}">
  {% block css %}{% endblock %}
</head>
<body>
  <div id="header">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'blog:post_list' %}">Mrfox</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="{% if section == "blog" %}active{% endif %}"><a href="{% url 'blog:post_list' %}">Blog</a></li>
            <li><a href="#">Shortcut</a></li>
          </ul>
          <form class="navbar-form navbar-left">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
            {% if not user.is_authenticated %}
            <li><a href="{% url 'account:login' %}">Login</a></li>
            {% else %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle"
                data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user }} <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="/report/">Report</a></li>
                <li><a href="{% url 'upload:upload' %}">Upload</a></li>
                <li><a href="{% url 'chat:contact' %}">Chat</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="{% url 'account:logout' %}">Logout</a></li>
              </ul>
            </li>
            {% endif %}
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </div>
  {% spaceless %}
  <div id="content" class="clearfix">
    {% block content %}
      <div id="main" class="fl">
        {% block main %}
        {% endblock %}
      </div>
      <div id="sidebar" class="fl">
        {% block sidebar %}
          {% if user.is_authenticated %}
            <h3>My Posts</h3>
            <ul>
            {% my_posts user as iposts %}
            {% for post in iposts %}
              <li><a href="{{ post.get_absolute_url }}">{{ post.title|truncatechars:30 }}</a></li>
            {% empty %}
              <li><a href="{% url 'blog:post_create' %}">create first one</a>.</li>
            {% endfor %}
            </ul>
          {% endif %}
          {% latest_posts as nposts %}
          <h3>Latest Posts</h3>
          <ul>
            {% for post in nposts %}
              <li><a href="{{ post.get_absolute_url }}">{{ post.title|truncatechars:30 }}</a></li>
            {% empty %}
              <li>No Posts</li>
            {% endfor %}
          </ul>
        {% endblock %}
      </div>
    {% endblock %}
  </div>
  {% endspaceless %}
  <div id="footer">
    <div class="powered-by">
      <h4>Powered by</h4>
      <ul>
        <li><a href="https://www.bootcss.com/">Bootstrap中文网</a></li>
        <li><a href="https://www.bootcdn.cn/">BootCDN</a></li>
        <li><a href="http://glyphicons.com/">Glyphicons</a></li>
      </ul>
    </div>
    <div class="about">
      <h4>About us</h4>
    </div>
    <div class="info">
      <h4>More info</h4>
    </div>
  </div>
  <script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"
    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <script>
    $(document).ready(function(){
      {% block domready %}
      {% endblock %}
    });
  </script>
  {% block js %}{% endblock %}
</body>
</html>

blog/templates/blog/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>技术学习记录</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <style>
    #curtain {
      min-height: 720px;
      background-image: url("{% static 'img/curtain.jpg' %}");
      background-repeat: no-repeat;
      background-size: cover;
      background-position: center;
      color: white;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="jumbotron" id="curtain">
      <h1>欢迎来到技术学习记录</h1>
      <p>
        个人技术开发的记录，分享技术相关的学习经验
      </p>
    </div>
    <div class="footer">
      <div class="text-center" style="color:#939393;">
        <a href="http://www.beian.miit.gov.cn" target="_blank">皖ICP备2020019891号-1</a>
        | <a target="_blank" href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=34030002020749"><img src="{% static "img/beian.png" %}" /><span>皖公网安备 34030002020749号</span></a>
</div>

        <!-- |<a href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=42018502000107" target="_blank">鄂公网安备 42018502000107号</a> -->
      </div>
    </div>
  </div>
  <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}

{% block content %}
  <form action="." method="post">
    {% csrf_token %}
    <p>Are you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
  </form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% load static %}

{% block title %}
  {{ post.title }}
{% endblock %}

{% block main %}
  <h3>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
  </h3>
  {% if user == post.author %}
  <a href="{% url 'blog:post_edit' post.pk %}"><span class="glyphicon glyphicon-pencil"></span> Edit</a>
  <a href="{% url 'blog:post_del' post.pk %}"><span class="glyphicon glyphicon-trash"></span> Delete</a>
  {% endif %}
  <p class="tags">
    {% with all_tags=post.tags.all %}
    <span class="tags">
      {% spaceless %}
      {% for tag in all_tags %}
      <span class="tag">
        <a href="{% url 'blog:post_tag_list' tag.slug %}"><span class="glyphicon glyphicon-tag"></span>{{ tag.name }}</a>
      </span>
      {% endfor %}
      {% endspaceless %}
    </span>
    {% if request.user == post.author %}
      <a href="javascript:void(0);" id='set-tag'>
        Edit Tag
      </a>
      <div class="modal">
        <div class="tag-edit">
          <div class="modal-title">
            Edit Tag
            <span class='close'>x</span>
          </div>
          <div class="new-tag">
            <div>Tags split by space.</div>
            <input type="text" name='new-tag' class="tags">
            <input type="submit" value="Add Tag">
            <span class="hint"></span>
          </div>
          <div class="current-tags">
            Current Tags:
            {% for tag in all_tags %}
              <span class="tag">
                {{ tag.name }}
                <span class="close del"></span>
              </span>
            {% empty %}
              <i>No tag so far.</i>
            {% endfor %}
          </div>
          <div class="canditate-tags">
            Common Tags:
          </div>
          <form action="{% url 'blog:post_tag_set' %}" method="POST" id="tag" class="hide">
            {% csrf_token %}
            <select name="tags" multiple></select>
            <input type="text" name='post_id' value="{{ post.pk }}">
          </form>
          <div class="clearfix">
            <button class="pull-right">Cancel</button>
            <input id="tag-submit" class="pull-right" type="submit" value="Save Tags">
          </div>
        </div>
      </div>
    {% endif %}
    {% endwith %}
  </p>
  <p class="date">
    Published {{ post.publish }} by {{ post.author }}
  </p>
  {{ post.normalized_body|markdown }}
{% endblock %}

{% block js %}
<script src='{% static "blog/js/tag.js" %}'></script>
{% endblock %}

{% block domready %}
window.postTagListURL = "{% url 'blog:post_tag_list' 'tobereplaced' %}";
{% endblock %}

blog/templates/blog/post_form.html
{% extends "blog/base.html" %}

{% block title %}
  Create new blog
{% endblock %}

{% block content %}
  <form action="." method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Save and Post">
  </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block title %}
  Blogs
{% endblock %}

{% block main %}
  <h1>Blogs</h1>
  {% if request.user.is_authenticated %}
    <a href="{% url 'blog:post_create' %}">Create Blog</a>
  {% endif %}
  {% for post in posts %}
    <h3>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </h3>
    <div class="edit-tool">
      {% if user == post.author %}
      <a href="{% url 'blog:post_edit' post.pk %}">Edit <span class="glyphicon glyphicon-pencil"></span></a>
      <a href="{% url 'blog:post_del' post.pk %}">Delete <span class="glyphicon glyphicon-trash"></span></a>
      {% endif %}
    </div>
    <p class="date">
      {% if post.status == "published" %}
      Published {{ post.publish }} by {{ post.author }}
      {% else %}
      Draft created in {{ post.created }} by {{ post.author }}
      {% endif %}
    </p>
    {{ post.body|truncatechars:140|linebreaks }}
    {% if not forloop.last %}
    <hr>
    {% endif %}
  {% endfor %}
  {% if is_paginated %}
    {% include "pagination.html" with page=page_obj %}
  {% endif %}
{% endblock %}